export const questSheetConfig = {
    questNoLabel: 'Quest No',
    metaLabels: {
        recommendedTool: '推奨ツール',
        difficulty: '難易度',
        questTier: 'クエスト段階',
        targetLevel: '対象レベル',
        experiencePoints: '獲得XP',
        acquiredSkill: '獲得スキル',
    },
    sections: {
        overview: '1. クエストの概要',
        purpose: '2. 目的',
        deliverable: '3. 提出物',
        completionCondition: '4. 完了条件',
    },
    emptySection: '—',
    backToNotebook: 'クエスト一覧に戻る',
    loading: '読み込み中...',
    loadQuestFailed: 'クエストの取得に失敗しました。',
    openDetailLink: '詳細ページを見る',
    deliverable: {
        urlLabel: 'リンクURL',
        textPlaceholder: '提出するテキストを入力',
        urlPlaceholder: 'https://docs.google.com/...',
        submitLabel: '提出する',
        submittingLabel: '提出中...',
        savedLabel: '提出済み',
        openLinkLabel: '提出物を開く',
        invalidUrl: '有効なURLを入力してください。',
        submitFailed: '提出物の保存に失敗しました。',
        submitSuccess: '提出物を保存しました。',
    },
} as const;
